#!/bin/sh
#
# Xcode Cloud — post-clone script.
# Runs after Xcode Cloud clones the repo, before the build starts.
#
# What this does: materializes `Config.swift` from secret environment variables
# defined in App Store Connect → Xcode Cloud → Workflow → Environment.
#
# Required secret env vars (mark as "Secret" in App Store Connect):
#   SUPABASE_URL              e.g. https://abcdefgh.supabase.co
#   SUPABASE_ANON_KEY         the anon (public) key — NOT the service_role key
#
# Documented in docs/CICD.md.

set -euo pipefail

echo "▶︎ ci_post_clone: materializing Config.swift from environment"

if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  echo "❌ SUPABASE_URL and SUPABASE_ANON_KEY must be set as Xcode Cloud secrets"
  echo "   App Store Connect → Your App → Xcode Cloud → Workflow → Environment → +"
  exit 1
fi

# CI_PRIMARY_REPOSITORY_PATH is set by Xcode Cloud and points at the repo root.
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
CONFIG_PATH="$REPO_ROOT/ios/TranscriptionAPPMVP/Config.swift"

cat > "$CONFIG_PATH" <<EOF
import Foundation

// AUTO-GENERATED by ci_scripts/ci_post_clone.sh during Xcode Cloud build.
// Do not commit. See Config.swift.example for the template.
enum Config {
    static let supabaseURL = URL(string: "${SUPABASE_URL}")!
    static let supabaseAnonKey = "${SUPABASE_ANON_KEY}"
    static let storageBucket = "recordings"
    static let audioSegmentSeconds: TimeInterval = 30
}
EOF

echo "✓ Config.swift written to $CONFIG_PATH"
